"""Contratos de dominio para el dataset canónico."""

from app.domain.contracts import (
    CANONICAL_FIELDS,
    CanonicalField,
    Editability,
    FieldOrigin,
    Sensitivity,
    get_canonical_field,
)
from app.domain.column_standards import ColumnVisibility, get_column_visibility, is_coverage_column, visible_column_names
from app.domain.policy_expirations import (
    STATUS_ACTIVE,
    STATUS_EXPIRED,
    STATUS_EXPIRING_SOON,
    STATUS_INVALID_DATE,
    STATUS_NOTICE_NOT_APPLICABLE,
    ExpirationEvaluation,
    calculate_due_date,
    classify_policy_expiration,
)
from app.domain.workbook_rules import (
    FREQUENCY_ANNUAL,
    FREQUENCY_DM,
    FREQUENCY_EMPTY,
    FREQUENCY_MONTHLY,
    FREQUENCY_OTHER,
    FREQUENCY_QUARTERLY,
    FREQUENCY_SEMIANNUAL,
    classify_frequency,
    classify_identification_format,
    classify_policy_number,
    consolidate_due_date,
    infer_currency,
)

__all__ = [
    "CANONICAL_FIELDS",
    "CanonicalField",
    "ColumnVisibility",
    "Editability",
    "ExpirationEvaluation",
    "FREQUENCY_ANNUAL",
    "FREQUENCY_DM",
    "FREQUENCY_EMPTY",
    "FREQUENCY_MONTHLY",
    "FREQUENCY_OTHER",
    "FREQUENCY_QUARTERLY",
    "FREQUENCY_SEMIANNUAL",
    "FieldOrigin",
    "Sensitivity",
    "STATUS_ACTIVE",
    "STATUS_EXPIRED",
    "STATUS_EXPIRING_SOON",
    "STATUS_INVALID_DATE",
    "STATUS_NOTICE_NOT_APPLICABLE",
    "calculate_due_date",
    "classify_frequency",
    "classify_identification_format",
    "classify_policy_expiration",
    "classify_policy_number",
    "consolidate_due_date",
    "get_column_visibility",
    "get_canonical_field",
    "infer_currency",
    "is_coverage_column",
    "visible_column_names",
]
